import { useQuery } from '@tanstack/react-query';
import { useParams } from 'react-router';

import {
  demos,
  exampleComponentMaps,
  examplesMeta,
} from '@/app/demo/[name]/index';
import { Renderer } from '@/app/demo/[name]/renderer';
import { ComponentPageLayout } from '@/components/registry/component-page-layout';
import { getComponentDocs } from '@/lib/docs';
import { type ComponentAPI, getRegistryItem } from '@/lib/registry';

/**
 * Fetch API documentation JSON for a component
 */
async function fetchAPIData(
  componentName: string,
): Promise<ComponentAPI[] | null> {
  try {
    const response = await fetch(
      `${import.meta.env.BASE_URL}api/${componentName}.json`,
    );
    if (!response.ok) {
      return null;
    }
    return response.json();
  } catch {
    return null;
  }
}

/**
 * Fetch pre-extracted example code from JSON (generated by scripts/extract-examples.ts).
 * Also loads companion files (e.g. input-group-examples.json) and merges them.
 */
async function fetchExampleCodeMap(
  componentName: string,
): Promise<Record<string, string> | null> {
  const codeMap: Record<string, string> = {};
  const jsonNames = [componentName, `${componentName}-examples`];

  for (const jsonName of jsonNames) {
    try {
      const response = await fetch(
        `${import.meta.env.BASE_URL}examples/${jsonName}.json`,
      );
      if (!response.ok) {
        continue;
      }
      const examples: Array<{ name: string; code: string }> =
        await response.json();
      for (const example of examples) {
        codeMap[example.name] = example.code;
      }
    } catch {
      // Try next name
    }
  }

  return Object.keys(codeMap).length > 0 ? codeMap : null;
}

/**
 * Check if a demo uses the new format
 */
function hasNewFormat(componentName: string): boolean {
  return componentName in examplesMeta && componentName in exampleComponentMaps;
}

export default function RegistryItemPage() {
  const { name } = useParams<{ name: string }>();

  const component = name ? getRegistryItem(name) : undefined;

  const isNewFormat = name ? hasNewFormat(name) : false;

  // Fetch API docs
  const { data: apiData } = useQuery({
    queryKey: ['api-docs', name],
    queryFn: () => fetchAPIData(name!),
    enabled: !!name,
  });

  // Fetch example code map (only for new format components)
  const { data: exampleCodeMap } = useQuery({
    queryKey: ['examples', name],
    queryFn: () => fetchExampleCodeMap(name!),
    enabled: !!name && isNewFormat,
  });

  if (!component || !name) {
    return (
      <div className="bg-surface-base flex min-h-screen w-full items-center justify-center p-5">
        <p className="text-fg-secondary paragraph-large-primary">
          Component not found.
        </p>
      </div>
    );
  }

  // Get demo configuration
  const demo = demos[component.name];

  // Get examples metadata and components for new format
  const examples = isNewFormat ? examplesMeta[component.name] : undefined;
  const exampleComponents = isNewFormat
    ? exampleComponentMaps[component.name]
    : undefined;

  // Build rendered example components for the layout
  const renderedExampleComponents = exampleComponents
    ? Object.fromEntries(
        Object.entries(exampleComponents).map(([key, Component]) => [
          key,
          <Renderer key={key}>
            <Component />
          </Renderer>,
        ]),
      )
    : undefined;

  // Get primary example for hero section
  const primaryExampleName = examples?.[0]?.name;
  const PrimaryExampleComponent =
    primaryExampleName && exampleComponents
      ? exampleComponents[primaryExampleName]
      : undefined;
  const primaryExample = PrimaryExampleComponent ? (
    <Renderer>
      <PrimaryExampleComponent />
    </Renderer>
  ) : undefined;
  const primaryExampleCode =
    primaryExampleName && exampleCodeMap
      ? exampleCodeMap[primaryExampleName]
      : undefined;

  // Build legacy preview content for backwards compatibility
  const legacyPreviewContent = demo?.components ? (
    <div className="flex w-full flex-col gap-4">
      {Object.entries(demo.components).map(([key, node]) => (
        <div className="relative mb-4 w-full" key={key}>
          <Renderer>{node}</Renderer>
        </div>
      ))}
    </div>
  ) : null;

  const docs = name ? getComponentDocs(name) : undefined;

  return (
    <div className="bg-surface-base min-h-screen w-full p-5 md:p-10">
      <div className="mx-auto w-full max-w-[800px]">
        <ComponentPageLayout
          component={component}
          apiData={apiData || undefined}
          useLegacyPreview={!isNewFormat}
          legacyPreviewContent={legacyPreviewContent}
          examples={examples}
          exampleComponents={renderedExampleComponents}
          exampleCodeMap={exampleCodeMap || undefined}
          primaryExample={primaryExample}
          primaryExampleCode={primaryExampleCode}
          docs={docs}
        />
      </div>
    </div>
  );
}
