import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, '..');
const ICONS_DIR = join(REPO_ROOT, 'src/components/icons');
const SOURCE_DIR = join(
  REPO_ROOT,
  'node_modules/@material-symbols/svg-300/sharp',
);
const MANIFEST = join(ICONS_DIR, 'icons.json');

interface IconEntry {
  /** PascalCase React component name, also the filename stem. */
  name: string;
  /**
   * Google Material Symbols canonical snake_case name. Defaults to the
   * PascalCase->snake_case conversion of `name`.
   */
  source?: string;
}

interface IconManifest {
  icons: IconEntry[];
}

const HEADER = `// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run \`npm run icons:gen\`.`;

function pascalToSnake(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toLowerCase();
}

function extractPathD(svg: string, sourceName: string): string {
  // The svg-300 package ships a single <path d="…"/> per glyph. If that ever
  // changes (multi-path, fill-rule, transforms) we want a loud failure, not
  // silent truncation.
  const paths = [...svg.matchAll(/<path\b([^>]*)\/>/g)];
  if (paths.length === 0) {
    throw new Error(`No <path> element in source SVG for "${sourceName}".`);
  }
  if (paths.length > 1) {
    throw new Error(
      `Source SVG for "${sourceName}" contains ${paths.length} <path> elements; ` +
        `generator currently assumes one. Extend generate-icons.ts to support this icon.`,
    );
  }
  const attrs = paths[0][1];
  const dMatch = attrs.match(/\bd="([^"]+)"/);
  if (!dMatch) {
    throw new Error(`<path> in "${sourceName}" has no d attribute.`);
  }
  const forbidden = attrs.match(
    /\b(fill|stroke|transform|fill-rule|clip-path)=/,
  );
  if (forbidden) {
    throw new Error(
      `<path> in "${sourceName}" carries an unexpected "${forbidden[1]}" attribute; ` +
        `IconShell expects pure currentColor glyphs.`,
    );
  }
  return dMatch[1];
}

function renderComponent(name: string, d: string): string {
  return `${HEADER}
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function ${name}({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="${d}" />
    </svg>
  );
}
`;
}

function renderIndex(names: string[]): string {
  const lines = [...names]
    .sort((a, b) => a.localeCompare(b))
    .map(n => `export { ${n} } from './${n}';`);
  return `${HEADER}\n${lines.join('\n')}\n`;
}

function loadManifest(): IconManifest {
  const raw = readFileSync(MANIFEST, 'utf8');
  const parsed = JSON.parse(raw) as IconManifest;
  if (!Array.isArray(parsed.icons)) {
    throw new Error(`${MANIFEST} is missing an "icons" array.`);
  }
  const seen = new Set<string>();
  for (const entry of parsed.icons) {
    if (!entry.name || !/^[A-Z][A-Za-z0-9]*$/.test(entry.name)) {
      throw new Error(`Invalid icon name "${entry.name}" in manifest.`);
    }
    if (seen.has(entry.name)) {
      throw new Error(`Duplicate icon name "${entry.name}" in manifest.`);
    }
    seen.add(entry.name);
  }
  return parsed;
}

async function formatFile(filename: string, contents: string): Promise<string> {
  // Defer to the repo's prettier config so generated files match the same
  // rules as hand-authored ones (line length, trailing commas, etc.).
  const config = await prettier.resolveConfig(join(ICONS_DIR, filename));
  return prettier.format(contents, { ...config, parser: 'typescript' });
}

async function generate(): Promise<Map<string, string>> {
  const { icons } = loadManifest();
  const raw = new Map<string, string>();

  for (const entry of icons) {
    const source = entry.source ?? pascalToSnake(entry.name);
    const svgPath = join(SOURCE_DIR, `${source}.svg`);
    if (!existsSync(svgPath)) {
      throw new Error(
        `Source SVG not found: ${svgPath}\n` +
          `  Icon "${entry.name}" resolves to source name "${source}".\n` +
          `  Either fix the manifest entry or pin a "source" override.`,
      );
    }
    const svg = readFileSync(svgPath, 'utf8');
    const d = extractPathD(svg, source);
    raw.set(`${entry.name}.tsx`, renderComponent(entry.name, d));
  }

  raw.set('index.ts', renderIndex(icons.map(i => i.name)));

  const outputs = new Map<string, string>();
  for (const [filename, contents] of raw) {
    outputs.set(filename, await formatFile(filename, contents));
  }
  return outputs;
}

function writeAll(outputs: Map<string, string>): void {
  if (!existsSync(ICONS_DIR)) {
    mkdirSync(ICONS_DIR, { recursive: true });
  }
  for (const [filename, contents] of outputs) {
    writeFileSync(join(ICONS_DIR, filename), contents);
  }
  // Remove stale generated files (any .tsx/index.ts in the folder that the
  // manifest no longer lists).
  const existing = readdirSync(ICONS_DIR).filter(
    f => f.endsWith('.tsx') || f === 'index.ts',
  );
  for (const f of existing) {
    if (!outputs.has(f)) {
      // Leave it alone — `icons.json` only owns files it generated. Print so
      // the human notices.
      console.warn(
        `[icons:gen] note: ${f} is in src/components/icons/ but not in icons.json`,
      );
    }
  }
}

function checkAll(outputs: Map<string, string>): number {
  let drift = 0;
  for (const [filename, expected] of outputs) {
    const path = join(ICONS_DIR, filename);
    if (!existsSync(path)) {
      console.error(`[icons:gen --check] missing: ${filename}`);
      drift += 1;
      continue;
    }
    const actual = readFileSync(path, 'utf8');
    if (actual !== expected) {
      console.error(`[icons:gen --check] out of date: ${filename}`);
      drift += 1;
    }
  }
  return drift;
}

async function main(): Promise<void> {
  const mode = process.argv.includes('--check') ? 'check' : 'write';
  const outputs = await generate();

  if (mode === 'check') {
    const drift = checkAll(outputs);
    if (drift > 0) {
      console.error(
        `\n${drift} icon file(s) out of date. Run \`npm run icons:gen\` and commit the result.`,
      );
      process.exit(1);
    }
    console.log(`[icons:gen --check] ${outputs.size} files up to date.`);
  } else {
    writeAll(outputs);
    console.log(
      `[icons:gen] wrote ${outputs.size} files to src/components/icons/.`,
    );
  }
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
