import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ICONS_DIR = resolve(SCRIPT_DIR, '../src/components/icons');
const MANIFEST = join(ICONS_DIR, 'icons.json');

// QBDS spec: Sharp style, 24dp source, weight 300, fill = 0. Pulled live
// from Google's master so we always match their canonical glyph bytes.
const SOURCE_URL = (name: string) =>
  `https://raw.githubusercontent.com/google/material-design-icons/master/symbols/web/${name}/materialsymbolssharp/${name}_wght300_24px.svg`;

interface IconEntry {
  name: string;
  source?: string;
}

const HEADER = `// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run \`npm run icons:gen\`.`;

function pascalToSnake(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toLowerCase();
}

function extractPathD(svg: string, source: string): string {
  const match = svg.match(/<path[^>]*\bd="([^"]+)"/);
  if (!match)
    throw new Error(`No <path d="…"/> in source SVG for "${source}".`);
  return match[1];
}

async function fetchPath(source: string): Promise<string> {
  const res = await fetch(SOURCE_URL(source));
  if (!res.ok) {
    throw new Error(
      `Failed to fetch "${source}" from Google (${res.status}). ` +
        `Check the source name or your network.`,
    );
  }
  return extractPathD(await res.text(), source);
}

function renderComponent(name: string, d: string): string {
  return `${HEADER}
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function ${name}({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="${d}" />
    </svg>
  );
}
`;
}

function renderIndex(names: string[]): string {
  const lines = [...names]
    .sort((a, b) => a.localeCompare(b))
    .map(n => `export { ${n} } from './${n}';`);
  return `${HEADER}\n${lines.join('\n')}\n`;
}

async function format(filename: string, contents: string): Promise<string> {
  const config = await prettier.resolveConfig(join(ICONS_DIR, filename));
  return prettier.format(contents, { ...config, parser: 'typescript' });
}

async function build(): Promise<Map<string, string>> {
  const { icons } = JSON.parse(readFileSync(MANIFEST, 'utf8')) as {
    icons: IconEntry[];
  };
  const files = new Map<string, string>();
  for (const { name, source } of icons) {
    const d = await fetchPath(source ?? pascalToSnake(name));
    files.set(
      `${name}.tsx`,
      await format(`${name}.tsx`, renderComponent(name, d)),
    );
  }
  files.set(
    'index.ts',
    await format('index.ts', renderIndex(icons.map(i => i.name))),
  );
  return files;
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const files = await build();
  let drift = 0;

  for (const [filename, expected] of files) {
    const path = join(ICONS_DIR, filename);
    if (check) {
      const actual = readFileSync(path, 'utf8');
      if (actual !== expected) {
        console.error(`[icons:gen --check] out of date: ${filename}`);
        drift += 1;
      }
    } else {
      writeFileSync(path, expected);
    }
  }

  if (check && drift > 0) {
    console.error(
      `\n${drift} icon file(s) out of date. Run \`npm run icons:gen\` and commit.`,
    );
    process.exit(1);
  }
  console.log(
    check
      ? `[icons:gen --check] ${files.size} files up to date.`
      : `[icons:gen] wrote ${files.size} files to src/components/icons/.`,
  );
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
