// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

type IconSize = 'sm' | 'default' | 'lg';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
  readonly size?: IconSize;
}

const PATHS: Record<IconSize, string> = {
  sm: 'M444-444H240v-72h204v-204h72v204h204v72H516v204h-72v-204Z',
  default: 'M450-450H220v-60h230v-230h60v230h230v60H510v230h-60v-230Z',
  lg: 'M454.87-454.87H220v-50.26h234.87V-740h50.26v234.87H740v50.26H505.13V-220h-50.26v-234.87Z',
};

export function Add({
  className,
  size = 'default',
  ...props
}: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d={PATHS[size]} />
    </svg>
  );
}
