// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function Backspace({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="M443.38-338.31 553.08-448l109.69 109.69 33-32.61L585.08-480l109.07-109.08-32.61-32.61L553.08-512l-109.7-109.69-32.61 32.61L521.08-480 410.77-370.92l32.61 32.61ZM327.31-180 100-480l226.69-300h533.92v600h-533.3ZM156.92-480 350-225.39h465.23v-509.22H350L156.92-480Zm329.16 0Z" />
    </svg>
  );
}
