// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function CropFree({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="M140-140v-214.31h45.39v168.92h168.92V-140H140Zm465.69 0v-45.39h168.92v-168.92H820V-140H605.69ZM140-605.69V-820h214.31v45.39H185.39v168.92H140Zm634.61 0v-168.92H605.69V-820H820v214.31h-45.39Z" />
    </svg>
  );
}
