// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function DisabledByDefault({
  className,
  ...props
}: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="M185.39-185.39h589.22v-589.22H185.39v589.22ZM140-140v-680h680v680H140Zm196-164.39 144-144 144 144L655.61-336l-144-144 144-144L624-655.61l-144 144-144-144L304.39-624l144 144-144 144L336-304.39Zm-150.61 119v-589.22 589.22Z" />
    </svg>
  );
}
