// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

type IconSize = 'sm' | 'default' | 'lg';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
  readonly size?: IconSize;
}

const PATHS: Record<IconSize, string> = {
  sm: 'M216-216h528v-528H216v528Zm-72 72v-672h672v672H144Zm206-155 130.19-130.19L610.37-299 661-349.63 530.81-479.81 661-610l-51-51-130.19 130.19L349.63-661 299-610.37l130.19 130.18L299-350l51 51Zm-134 83v-528 528Z',
  default:
    'M200-200h560v-560H200v560Zm-60 60v-680h680v680H140Zm196-154.23 144-144 144 144L665.77-336l-144-144 144-144L624-665.77l-144 144-144-144L294.23-624l144 144-144 144L336-294.23ZM200-200v-560 560Z',
  lg: 'M190.26-190.26h579.48v-579.48H190.26v579.48ZM140-140v-680h680v680H140Zm196-161 144-144 144 144 35-35-144-144 144-144-35-35-144 144-144-144-35 35 144 144-144 144 35 35ZM190.26-190.26v-579.48 579.48Z',
};

export function DisabledByDefault({
  className,
  size = 'default',
  ...props
}: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d={PATHS[size]} />
    </svg>
  );
}
