// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function Key({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="M240.65-440.65Q224.31-457 224.31-480t16.34-39.35Q257-535.69 280-535.69t39.35 16.34Q335.69-503 335.69-480t-16.34 39.35Q303-424.31 280-424.31t-39.35-16.34ZM280-260q-91.54 0-155.77-64.23T60-480q0-91.54 64.23-155.77T280-700q67.77 0 119.65 34 51.89 34 78.27 98.39h362.93l94.92 94.92-144.31 133.38-79.92-58.61-82.23 59.38-70.77-53.85h-80.62q-22.31 57.7-73.69 95.04Q352.85-260 280-260Zm0-45.39q58.77 0 105.65-38.11 46.89-38.12 60.12-94.27h129.38l54.77 42.69 82.62-58.77 75.84 57.39 81.93-77.85-47.93-47.92H445.77q-11.62-53.31-57.89-92.85-46.26-39.53-107.88-39.53-72.69 0-123.65 50.96-50.96 50.96-50.96 123.65t50.96 123.65q50.96 50.96 123.65 50.96Z" />
    </svg>
  );
}
