// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function Layers({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="M480-173.08 152.31-427.69l37.31-28.16L480-230.62l290.38-225.23 37.31 28.16L480-173.08Zm0-140.85L152.31-568.54 480-823.15l327.69 254.61L480-313.93Zm0-269.84Zm0 212.31 253.54-197.08L480-765.23 226.46-568.54 480-371.46Z" />
    </svg>
  );
}
