// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

type IconSize = 'sm' | 'default' | 'lg';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
  readonly size?: IconSize;
}

const PATHS: Record<IconSize, string> = {
  sm: 'M192-96v-528h96v-96q0-79.68 56.23-135.84 56.22-56.16 136-56.16Q560-912 616-855.84q56 56.16 56 135.84v96h96v528H192Zm72-72h432v-384H264v384Zm216.21-120Q510-288 531-309.21t21-51Q552-390 530.79-411t-51-21Q450-432 429-410.79t-21 51Q408-330 429.21-309t51 21ZM360-624h240v-96q0-50-35-85t-85-35q-50 0-85 35t-35 85v96Zm-96 456v-384 384Z',
  default:
    'M180-100v-520h120v-80q0-74.92 52.54-127.46Q405.08-880 480-880q74.92 0 127.46 52.54Q660-774.92 660-700v80h120v520H180Zm60-60h480v-400H240v400Zm240-130q29.15 0 49.58-20.42Q550-330.85 550-360t-20.42-49.58Q509.15-430 480-430t-49.58 20.42Q410-389.15 410-360t20.42 49.58Q450.85-290 480-290ZM360-620h240v-80q0-50-35-85t-85-35q-50 0-85 35t-35 85v80ZM240-160v-400 400Z',
  lg: 'M180-100v-517.02h124.87v-87.85q0-72.9 51.14-124.01Q407.15-880 480.09-880t123.99 51.12q51.05 51.11 51.05 124.01v87.85H780V-100H180Zm50.26-50.26h499.48v-416.51H230.26v416.51ZM480.11-290q28.38 0 48.39-19.83t20.01-47.86q0-27.41-20.12-48.37-20.13-20.96-48.5-20.96-28.38 0-48.39 20.96t-20.01 48.7q0 27.74 20.12 47.55Q451.74-290 480.11-290ZM355.13-617.02h249.74v-87.85q0-52.03-36.39-88.45-36.4-36.42-88.39-36.42t-88.47 36.42q-36.49 36.42-36.49 88.45v87.85ZM230.26-150.26v-416.51 416.51Z',
};

export function Lock({
  className,
  size = 'default',
  ...props
}: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d={PATHS[size]} />
    </svg>
  );
}
