// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function PageInfo({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="M611.19-205.42q-38.88-38.89-38.88-94.97 0-56.07 38.88-94.96 38.89-38.88 94.96-38.88 56.08 0 94.96 38.88Q840-356.46 840-300.39q0 56.08-38.89 94.97-38.88 38.88-94.96 38.88-56.07 0-94.96-38.88ZM769-237.45q25.61-25.52 25.61-62.84 0-37.33-25.52-62.94-25.52-25.62-62.84-25.62-37.33 0-62.94 25.53-25.62 25.52-25.62 62.84 0 37.33 25.52 62.94 25.53 25.62 62.85 25.62T769-237.45Zm-618.23-40.24v-45.39h333.85v45.39H150.77Zm8.12-286.96Q120-603.54 120-659.61q0-56.08 38.89-94.97 38.88-38.88 94.96-38.88 56.07 0 94.96 38.88 38.88 38.89 38.88 94.97 0 56.07-38.88 94.96-38.89 38.88-94.96 38.88-56.08 0-94.96-38.88Zm157.8-32.03q25.62-25.52 25.62-62.84 0-37.33-25.52-62.94-25.53-25.62-62.85-25.62T191-722.55q-25.61 25.52-25.61 62.84 0 37.33 25.52 62.94 25.52 25.62 62.84 25.62 37.33 0 62.94-25.53Zm158.69-40.24v-45.39h333.85v45.39H475.38Zm230.77 336.53Zm-452.3-359.22Z" />
    </svg>
  );
}
