// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function PlaylistAddCheck({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="M130-330v-60h300v60H130Zm0-160v-60h460v60H130Zm0-160v-60h460v60H130Zm524 436.15L525.85-342 568-384.15l86 84.77 170-170L866.15-426 654-213.85Z" />
    </svg>
  );
}
