// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function ProgressActivity({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="M331.32-129.4q-69.29-29.4-120.9-81.02-51.62-51.61-81.02-120.9-29.4-69.3-29.4-148.73 0-79.43 29.46-148.73 29.46-69.3 80.96-120.8 51.5-51.5 120.93-80.96Q400.78-860 480-860v45.39q-138.69 0-236.65 97.96-97.96 97.96-97.96 236.65t97.96 236.65q97.96 97.96 236.65 97.96t236.65-97.96q97.96-97.96 97.96-236.65H860q0 79.22-29.46 148.65t-80.96 120.93q-51.5 51.5-120.8 80.96Q559.48-100 480.05-100q-79.43 0-148.73-29.4Z" />
    </svg>
  );
}
