// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

type IconSize = 'sm' | 'default' | 'lg';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
  readonly size?: IconSize;
}

const PATHS: Record<IconSize, string> = {
  sm: 'M480-96q-78.72 0-148.8-30.24-70.08-30.24-122.4-82.56-52.32-52.32-82.56-122.4Q96-401.28 96-480q0-79.68 30.24-149.28T208.8-751.2q52.32-52.32 122.4-82.56Q401.28-864 480-864v72q-130 0-221 90.5t-91 221Q168-350 259.16-259q91.17 91 220.84 91 131 0 221.5-91.16Q792-350.33 792-480h72q0 79-30.24 149.02-30.24 70.01-82.56 122.28-52.32 52.28-121.92 82.49Q559.68-96 480-96Z',
  default:
    'M479.88-100q-78.03 0-147.33-29.9-69.29-29.9-121.02-81.63-51.73-51.73-81.63-121.02-29.9-69.3-29.9-147.33 0-78.98 29.96-147.97 29.96-69 81.58-120.61 51.61-51.62 121.04-81.58T480-860v60q-133 0-226.5 93.5T160-480q0 133 93.5 226.5T480-160q133 0 226.5-93.5T800-480h60q0 77.99-29.96 147.42-29.96 69.43-81.58 121.04-51.61 51.62-120.61 81.58Q558.86-100 479.88-100Z',
  lg: 'M479.88-100q-78.85 0-148.15-29.57-69.29-29.56-120.94-81.22-51.66-51.65-81.22-120.94Q100-401.03 100-479.88q0-79.21 29.63-148.5T210.8-749.2q51.53-51.54 120.96-81.17Q401.19-860 480-860v50.26q-137 0-233.37 96.32-96.37 96.33-96.37 233.27t96.32 233.42q96.33 96.47 233.27 96.47t233.42-96.37Q809.74-343 809.74-480H860q0 78.81-29.63 148.24T749.2-210.8q-51.53 51.54-120.82 81.17Q559.09-100 479.88-100Z',
};

export function ProgressActivity({
  className,
  size = 'default',
  ...props
}: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d={PATHS[size]} />
    </svg>
  );
}
