// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function Style({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="m165.92-158-94.53-40.92 94.53-204.77V-158Zm95.39-203.54L361.69-82.31H261.31v-279.23ZM464.77-81.39 244.23-686.46l415.92-151.77 220.93 604.69L464.77-81.39ZM442.85-560q17 0 28.5-11.5t11.5-28.5q0-17-11.5-28.5t-28.5-11.5q-17 0-28.5 11.5t-11.5 28.5q0 17 11.5 28.5t28.5 11.5Zm58 400 302-110-178-490-302 110 178 490Zm-178-490 302-110-302 110Z" />
    </svg>
  );
}
