// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

type IconSize = 'sm' | 'default' | 'lg';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
  readonly size?: IconSize;
}

const PATHS: Record<IconSize, string> = {
  sm: 'm168-175-95-45 95-205v250Zm72-281L374-96H240v-360ZM455-77 234-680l429-157 222 608L455-77Zm-11.21-475q15.21 0 25.71-10.29t10.5-25.5q0-15.21-10.29-25.71t-25.5-10.5q-15.21 0-25.71 10.29t-10.5 25.5q0 15.21 10.29 25.71t25.5 10.5ZM498-168l294-105-171-471-294 107 171 469ZM327-637l294-107-294 107Z',
  default:
    'm165.92-158-94.53-40.92 94.53-204.77V-158Zm95.39-203.54L361.69-82.31H261.31v-279.23ZM464.77-81.39 244.23-686.46l415.92-151.77 220.93 604.69L464.77-81.39ZM442.85-560q17 0 28.5-11.5t11.5-28.5q0-17-11.5-28.5t-28.5-11.5q-17 0-28.5 11.5t-11.5 28.5q0 17 11.5 28.5t28.5 11.5Zm58 400 302-110-178-490-302 110 178 490Zm-178-490 302-110-302 110Z',
  lg: 'M162.54-146.77 71.8-181.33l90.74-201.38v235.94Zm107.03-193.38 93.61 264.2h-93.61v-264.2ZM475.59-88.82 255.46-690.26l405.1-146.89 221.59 600.23-406.56 148.1Zm-30.18-483.9q14.44 0 24.78-10.34 10.35-10.35 10.35-24.79 0-14.43-10.35-24.78-10.34-10.34-24.78-10.34-14.69 0-24.91 10.34-10.22 10.35-10.22 24.78 0 14.44 10.22 24.79 10.22 10.34 24.91 10.34Zm60.31 418 309.84-112.97-184.35-503.95-309.85 112.31 184.36 504.61ZM321.36-659.33l309.85-112.31-309.85 112.31Z',
};

export function Style({
  className,
  size = 'default',
  ...props
}: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d={PATHS[size]} />
    </svg>
  );
}
