// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function SwapVert({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="M336.16-453.85v-291.23L222.77-631.69 180-673.85 366.15-860l186.16 186.15-42.77 42.16-113.39-113.39v291.23h-59.99ZM593.46-100 407.31-286.15l42.77-42.16 113.38 113.39v-291.23h60v291.23l113.39-113.39 42.76 42.16L593.46-100Z" />
    </svg>
  );
}
