// AUTO-GENERATED by scripts/generate-icons.ts. Do not edit by hand.
// To add, remove, or rename an icon, update src/components/icons/icons.json
// and run `npm run icons:gen`.
import * as React from 'react';

import { cn } from '@/lib/utils';

interface IconProps extends React.SVGProps<SVGSVGElement> {
  readonly className?: string;
}

export function VolumeDown({ className, ...props }: Readonly<IconProps>) {
  return (
    <svg
      className={cn('', className)}
      viewBox="0 -960 960 960"
      fill="currentColor"
      aria-hidden="true"
      {...props}>
      <path d="M220-380v-200h148.46L540-751.53v543.06L368.46-380H220Zm400.77 51.84v-305.07q45.15 18.15 72.19 60.35Q720-530.69 720-480q0 51.69-27.04 92.69t-72.19 59.15ZM494.61-636.85 388.92-534.61H265.39v109.22h123.53l105.69 102.85v-314.31ZM378.38-480Z" />
    </svg>
  );
}
